### ISSUE TITLE
Yaru theme review - report icon bugs upstream

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#143]
This task will be complete when those issues I reported as part of #140, that are specifically about icons copied from the Suru theme, are also reported on [the Suru repo](https://github.com/snwh/suru-icon-theme) and the issues link to each other.

- [#855 Grabbing hand cursor is not recognizable](https://github.com/ubuntu/yaru/issues/855) _already reviewed by upstream maintainer_
- [x] [#859 Rhythmbox icon is not recognizable](https://github.com/ubuntu/yaru/issues/859)
- [x] [#861 No way to guess icons of Language Support vs. Software & Updates](https://github.com/ubuntu/yaru/issues/861)
- [x] [#862 Ubuntu Software and Software Updater icons differ only in color](https://github.com/ubuntu/yaru/issues/862)
- [x] [#863 Letter “A” is back-to-front in Ubuntu Software and Software Updater icons](https://github.com/ubuntu/yaru/issues/863)
- [x] [#864 Folders differ in aspect ratio for Files app icon vs. directory icons](https://github.com/ubuntu/yaru/issues/864)
- [x] [#865 Downloads symbol differs in aspect ratio for sidebar vs. folder icon](https://github.com/ubuntu/yaru/issues/865)
- [ ] [#866 Inconsistent rounded corners for file icons](https://github.com/ubuntu/yaru/issues/866)
- [#867 Desktop icons inconsistent with the Desktop and with each other](https://github.com/ubuntu/yaru/issues/867) _Ubuntu-specific_
- [x] [#868 Different kinds of Trash / Rubbish Bin in Desktop vs. sidebar](https://github.com/ubuntu/yaru/issues/868)
- [#869 Volume icons are a mixture of symbolic and app-style](https://github.com/ubuntu/yaru/issues/869) _not clear that it’s an upstream issue
